import{a as S,i as f,S as v}from"./assets/vendor-DFCQGEf1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const q="https://pixabay.com/api/",x="50239307-4265dc0f1525b6f9dda79b82a";async function p(e,o=1){try{const n=await S.get(q,{params:{key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}}),{hits:s}=n.data;return s}catch{return f.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight"}),[]}}const i=document.querySelector(".gallery"),m=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),y=document.querySelector(".end-of-collection");u.style.display="none";y.style.display="none";Object.assign(i.style,{display:"flex",flexDirection:"row",gap:"24px",flexWrap:"wrap",justifyContent:"center",margin:"24px"});i.addEventListener("click",M);function M(e){e.target.closest(".gallery-link")&&e.preventDefault()}function P(e){const o=e.tags.split(",").slice(0,3).join(", ");return`<li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${o}" />
    </a>
    <div class="image-info">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p>
      <p><b>Categories:</b> ${o}</p>
    </div>
  </li>`}function $(e){return e.map(P).join("")}function g(e,o){const n=$(e);i.insertAdjacentHTML("beforeend",n),O(),e.length===0&&f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),e.length>0&&L(),i.children.length>=100&&(d(),I()),new v(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"}).refresh()}function E(){i.innerHTML=""}function h(){m.classList.add("loader-show")}function b(){m.classList.remove("loader-show")}function L(){u.style.display="inline-block"}function d(){u.style.display="none"}function I(){y.style.display="inline-block"}function O(){const e=i.querySelector(".gallery-item");if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}let a=1,c="";const w=document.querySelector(".form"),k=w.querySelector('input[name="search-text"]'),B=document.querySelector(".load-more-btn");w.addEventListener("submit",C);B.addEventListener("click",R);async function C(e){e.preventDefault();const o=k.value.trim();if(o===""){iziToast.info({title:"Input Error",message:"Please enter a search term!",position:"topRight"});return}c=o,a=1,E(),h();const n=await p(c,a);b(),g(n),d(),L()}async function R(){a+=1,h();const e=await p(c,a);b(),g(e),e.length===0&&d()}
//# sourceMappingURL=index.js.map
