import{a as v,i as d,S as E}from"./assets/vendor-C2BD4WGs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&l(g)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const O="https://pixabay.com/api/",I="50239307-4265dc0f1525b6f9dda79b82a";async function h(e,t=1){try{const n=await v.get(O,{params:{key:I,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}}),{hits:l,totalHits:o}=n.data;return{hits:l,totalHits:o}}catch{return d.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight"}),{hits:[],totalHits:0}}}const s=document.querySelector(".gallery");document.querySelector(".loader");const y=document.querySelector(".load-more-btn"),m=document.querySelector(".end-of-collection");y.style.display="none";m.style.display="none";Object.assign(s.style,{display:"flex",flexDirection:"row",gap:"24px",flexWrap:"wrap",justifyContent:"center",margin:"24px"});const $=new E(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function P(e){const t=e.tags.split(",").slice(0,3).join(", ");return`<li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${t}" />
    </a>
    <div class="image-info">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p>
      <p><b>Categories:</b> ${t}</p>
    </div>
  </li>`}function R(e){return e.map(P).join("")}function b(e,t){const n=R(e);s.insertAdjacentHTML("beforeend",n),C(),console.log("Gallery children:",s.children.length),console.log("Total hits:",t),console.log("Show end message:",s.children.length>=t),$.refresh()}function T(){s.innerHTML=""}function w(){y.style.display="inline-block"}function f(){y.style.display="none"}function L(){m.style.display="block"}function B(){m.style.display="none"}function C(){const e=s.querySelector(".gallery-item");if(!e)return;const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}let u=1,a="",i=0,c=0;const S=document.querySelector(".form"),H=S.querySelector('input[name="search-text"]'),q=document.querySelector(".load-more-btn"),M=document.querySelector(".loading-text");S.addEventListener("submit",j);q.addEventListener("click",A);function x(){q.style.display="none",M.style.display="block"}function p(){M.style.display="none"}async function j(e){if(e.preventDefault(),a=H.value.trim(),!!a){u=1,i=0,c=0,T(),f(),B(),x();try{const{hits:t,totalHits:n}=await h(a,u);if(p(),i=t.length,c=n,t.length===0){d.error({message:"No images found for this query!",position:"topRight"});return}b(t),i>=c?(L(),f()):w()}catch{p(),d.error({message:"Error fetching images.",position:"topRight"})}}}async function A(){u++,x();try{const{hits:e}=await h(a,u);p(),i+=e.length,b(e),i>=c?(L(),f()):w()}catch{p(),d.error({message:"Error loading more images.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
